name: GitHub Metrics (isocalendar)

on:
  schedule:
    - cron: "23 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Lartweib
          filename: github-metrics.svg
          template: classic
          config_timezone: Europe/Madrid

          base: header, repositories
          repositories_affiliations: owner, collaborator, organization_member
          repositories_private: yes

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_categories: programming
          plugin_languages_colors: github

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half
